version: '3.8'

volumes:
  mongo_vol:

networks:
  rotten_network:
    driver: bridge

services:
  app:
    image: prhirata/rotten-potatoes:desafio
    build: 
      dockerfile: ./Dockerfile
      context: ./src
    ports:
      - 8080:5000
    networks:
      - rotten_network
    depends_on:
      - mongodb
    environment:
      MONGODB_DB: admin
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_USERNAME: mongouser
      MONGODB_PASSWORD: mongopwd
  
  mongodb:
    image: mongo:4.4.3
    ports:
      - 27017:27017
    networks:
      - rotten_network
    volumes:
      - mongo_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd